### ISSUE TITLE
Ajouter le logo Norauto

### ISSUE THREAD

**Issue by EmmanuelDemey** [GDG-Lille/devfest-lille#71]

**Comment by fgruchala** [comment]
Je m'occupe de ça dès que possible :) Sponsor Silver, c'est bien ça ?

**Comment by FannyDemey** [comment]
Non gold ;)

Le 12 janv. 2018 01:13, "François GRUCHALA" <notifications@github.com> a
écrit :

Je m'occupe de ça dès que possible :) Sponsor Silver, c'est bien ça ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GDG-Lille/devfest-lille/issues/71#issuecomment-357103705>,
or mute the thread
